// Application Constants

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  FARMER: 'FARMER',
  MANDI_OWNER: 'MANDI_OWNER',
  RESEARCHER: 'RESEARCHER',
  LAB_OWNER: 'LAB_OWNER',
  CONTENT_MANAGER: 'CONTENT_MANAGER'
};

export const CROP_CATEGORIES = {
  CEREALS: 'CEREALS',
  PULSES: 'PULSES',
  VEGETABLES: 'VEGETABLES',
  FRUITS: 'FRUITS',
  CASH_CROPS: 'CASH_CROPS',
  SPICES: 'SPICES'
};

export const NEWS_CATEGORIES = {
  FARMING: 'FARMING',
  TECHNOLOGY: 'TECHNOLOGY',
  MARKET: 'MARKET',
  GOVERNMENT: 'GOVERNMENT',
  WEATHER: 'WEATHER',
  RESEARCH: 'RESEARCH'
};

export const STATUS = {
  DRAFT: 'draft',
  PUBLISHED: 'published',
  ARCHIVED: 'archived'
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500
};
